global:
  scrape_interval: 10s

scrape_configs:
  - job_name: mysql
    static_configs:
      - targets:
        - db:3306
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: node_exporter:9104
  - job_name: node
    static_configs:
      - targets:
        - node_exporter:9104